# Title for the gitleaks configuration file.
title = "Add custom gitleaks config"

# Extend the base (this) configuration. When you extend a configuration
# the base rules take precendence over the extended rules. I.e, if there are
# duplicate rules in both the base configuration and the extended configuration
# the base rules will override the extended rules.
# Another thing to know with extending configurations is you can chain together
# multiple configuration files to a depth of 2. Allowlist arrays are appended
# and can contain duplicates.
# useDefault and path can NOT be used at the same time. Choose one.
[extend]
# useDefault will extend the base configuration with the default gitleaks config:
# https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml
useDefault = true


[[rules]]
id = "fury-auth-token"
description = "Identified a Gemfury auth token, which may compromise the security of the PyPI"
regex = '''(?:[0-9a-zA-Z]{5,6})-[0-9a-zA-Z]{25,27}'''
entropy = 3
[[rules.allowlists]]
paths = [
]
