name: Upload to PyPi

on:
  push:
    branches:
      - develop
      - main

jobs:
  push-to-testpypi:
    env:
      PACKAGE_INDEX_TOKEN: ${{ secrets.PACKAGE_INDEX_TOKEN }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Determine package index
        shell: bash
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "Branch name is: $BRANCH_NAME"
          [ $BRANCH_NAME = "main" ] && PACKAGE_INDEX='pypi' || PACKAGE_INDEX='testpypi'
          echo "Package index is: $PACKAGE_INDEX"
          echo "package_index=$PACKAGE_INDEX" >> $GITHUB_OUTPUT
        id: determine_package_index

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Download dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and push package to package index
        run: |
          python -m build
          twine upload --repository ${{ steps.determine_package_index.package_index }} dist/* -u __token__ -p '${PACKAGE_INDEX_TOKEN}'