name: Upload to PyPi

on:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'

jobs:
  push-to-testpypi:
    environment: ${{ github.ref_name }}
    env:
      PACKAGE_INDEX_TOKEN: ${{ secrets.PACKAGE_INDEX_TOKEN }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Download and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build package
        run: |
          python -m build

      - name: Push package to package index
        run: |
          echo "Uploading to 💎 GemFury 💎"
          FILE_NAME=`ls ./dist/ | grep .whl`
          curl -F package=@dist/$FILE_NAME https://'${{ secrets.PACKAGE_INDEX_TOKEN }}'@push.fury.io/felix-bedag/