name: Upload to PyPi

on:
  push:
    branches:
      - develop
      - main
    tags:
      - v*

jobs:
  push-to-testpypi:
    if: startsWith(github.ref, 'refs/tags/v') && (github.ref_name == 'develop' || github.ref_name == 'main')
    environment: ${{ github.ref_name }}
    env:
      PACKAGE_INDEX_TOKEN: ${{ secrets.PACKAGE_INDEX_TOKEN }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Determine package index
        shell: bash
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "Branch name is: $BRANCH_NAME"
          [ $BRANCH_NAME = "main" ] && PACKAGE_INDEX='pypi' || PACKAGE_INDEX='testpypi'
          echo "Package index is: $PACKAGE_INDEX"
          echo "package_index=$PACKAGE_INDEX" >> $GITHUB_OUTPUT
        id: determine_package_index

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Download and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build package
        run: |
          python -m build

      - name: Push package to package index
        run: |
          echo "Uploading to ${{ steps.determine_package_index.outputs.package_index }}"
          twine upload --repository ${{ steps.determine_package_index.outputs.package_index }} -u __token__ -p '${{ secrets.PACKAGE_INDEX_TOKEN }}' ./dist/* 